name = "workware-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "RATE_LIMIT"
class_name = "RateLimitDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimitDO"]
