ALTER TABLE products
  ADD COLUMN IF NOT EXISTS detail_info TEXT,
  ADD COLUMN IF NOT EXISTS shipping_info TEXT,
  ADD COLUMN IF NOT EXISTS return_info TEXT,
  ADD COLUMN IF NOT EXISTS thumbnail TEXT,
  ADD COLUMN IF NOT EXISTS badge TEXT,
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT false;
